# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octo < Formula
  desc "Toolbelt for your AWS ASGs"
  homepage "http://github.com/faizalzakaria"
  version "1.1.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/faizalzakaria/octo/releases/download/v1.1.1/octo_1.1.1_Darwin_arm64.tar.gz"
      sha256 "e747260a451c77b44e424b700eca0a0fc0b1de2c6fab7aca05f9ce12635c6564"

      def install
        bin.install "octo"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/faizalzakaria/octo/releases/download/v1.1.1/octo_1.1.1_Darwin_x86_64.tar.gz"
      sha256 "42244635601ee542ca79602c91a69c03643d362ac0706cba6efd64c7430c291a"

      def install
        bin.install "octo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/faizalzakaria/octo/releases/download/v1.1.1/octo_1.1.1_Linux_arm64.tar.gz"
      sha256 "7051a4d33cc3319aad0def6f8b9b0e603181963d355273a26ed9d5be652a0c34"

      def install
        bin.install "octo"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/faizalzakaria/octo/releases/download/v1.1.1/octo_1.1.1_Linux_x86_64.tar.gz"
      sha256 "4d3226c592c51c747b1edd9fba47a9b5ea4b404bd0ea2ed927b54b884553bfd2"

      def install
        bin.install "octo"
      end
    end
  end
end
